# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Angular
    init: |
      cd resistance
      npm install
    command: npx ng serve
  - name: GO
    init: |
      cd go-api
      go install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
