version: '3.9'

services:
  resistance:
    container_name: resistance
    build:
      context: ./ng-resistance
      dockerfile: ./Dockerfile
    ports:
      - 8081:80

  node-api:
    container_name: node_api
    build:
      context: ./node-api
      dockerfile: ./Dockerfile
    ports:
      - 4444:4444
